/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: "class",
  theme: {
    extend: {
      colors: {
        "secondary-fixed": "#ebe1d4",
        "surface-container-high": "#efe7e0",
        "on-tertiary-fixed-variant": "#514700",
        "tertiary": "#6b5f00",
        "surface-container-highest": "#e9e1da",
        "inverse-surface": "#34302b",
        "on-secondary": "#ffffff",
        "on-surface-variant": "#5a413b",
        "on-primary-fixed-variant": "#8c1900",
        "tertiary-fixed": "#f6e47b",
        "secondary-container": "#ebe1d4",
        "primary": "#b32705",
        "inverse-on-surface": "#f8efe8",
        "on-primary-fixed": "#3d0600",
        "surface-variant": "#e9e1da",
        "surface": "#fff8f3",
        "on-tertiary": "#ffffff",
        "secondary": "#645e53",
        "on-error-container": "#93000a",
        "background": "#fff8f3",
        "surface-container-low": "#fbf2eb",
        "on-secondary-fixed": "#1f1b13",
        "surface-container": "#f5ece5",
        "on-primary": "#ffffff",
        "outline-variant": "#e3beb6",
        "primary-fixed": "#ffdad2",
        "on-background": "#1e1b17",
        "on-error": "#ffffff",
        "surface-bright": "#fff8f3",
        "on-tertiary-container": "#484000",
        "surface-dim": "#e1d9d2",
        "on-tertiary-fixed": "#201c00",
        "tertiary-fixed-dim": "#d9c863",
        "inverse-primary": "#ffb4a3",
        "tertiary-container": "#bcac4b",
        "outline": "#8f7069",
        "surface-container-lowest": "#ffffff",
        "secondary-fixed-dim": "#cec5b9",
        "primary-fixed-dim": "#ffb4a3",
        "error-container": "#ffdad6",
        "error": "#ba1a1a",
        "on-secondary-container": "#6a6459",
        "on-primary-container": "#ffffff",
        "on-secondary-fixed-variant": "#4c463d",
        "primary-container": "#d6401f",
        "surface-tint": "#b42806",
        "on-surface": "#1e1b17"
      },
      borderRadius: {
        "DEFAULT": "0.125rem",
        "lg": "0.25rem",
        "xl": "0.375rem",
        "full": "9999px"
      },
      spacing: {
        "space-xs": "0.25rem",
        "space-sm": "0.5rem",
        "space-md": "1rem",
        "space-lg": "1.5rem",
        "space-xl": "2.5rem",
        "gutter": "1.5rem",
        "gutter-mobile": "1rem",
        "margin": "3rem",
        "margin-mobile": "1.25rem"
      },
      fontFamily: {
        "headline": ["Newsreader", "serif"],
        "headline-xl": ["Newsreader", "serif"],
        "headline-lg": ["Newsreader", "serif"],
        "headline-md": ["Newsreader", "serif"],
        "headline-sm": ["Newsreader", "serif"],
        "headline-xl-mobile": ["Newsreader", "serif"],
        "headline-lg-mobile": ["Newsreader", "serif"],
        "body": ["IBM Plex Sans", "sans-serif"],
        "body-lg": ["IBM Plex Sans", "sans-serif"],
        "body-md": ["IBM Plex Sans", "sans-serif"],
        "body-sm": ["IBM Plex Sans", "sans-serif"],
        "label": ["JetBrains Mono", "monospace"],
        "label-lg": ["JetBrains Mono", "monospace"],
        "label-md": ["JetBrains Mono", "monospace"],
        "label-sm": ["JetBrains Mono", "monospace"],
        "mono": ["JetBrains Mono", "monospace"]
      },
      fontSize: {
        "headline-xl": ["40px", { lineHeight: "48px", fontWeight: "600" }],
        "headline-xl-mobile": ["30px", { lineHeight: "36px", fontWeight: "600" }],
        "headline-lg": ["32px", { lineHeight: "40px", fontWeight: "500" }],
        "headline-lg-mobile": ["26px", { lineHeight: "34px", fontWeight: "500" }],
        "headline-md": ["24px", { lineHeight: "32px", fontWeight: "500" }],
        "headline-sm": ["20px", { lineHeight: "28px", fontWeight: "500" }],
        "body-lg": ["17px", { lineHeight: "27px", fontWeight: "400" }],
        "body-md": ["15px", { lineHeight: "24px", fontWeight: "400" }],
        "body-sm": ["14px", { lineHeight: "21px", fontWeight: "400" }],
        "label-lg": ["14px", { lineHeight: "20px", fontWeight: "500" }],
        "label-md": ["13px", { lineHeight: "18px", fontWeight: "400" }],
        "label-sm": ["11px", { lineHeight: "16px", fontWeight: "400" }]
      }
    },
  },
  plugins: [],
}
